### ISSUE TITLE
TypeError: Cannot read property "then" of undefined in readChunk()

### ISSUE THREAD

**Issue by alex-all3dp** [miratronix/s3-readable-stream#14]
We are occassionally encountering the following error
  
<img width="935" alt="Bildschirmfoto 2021-12-10 um 15 34 11" src="https://user-images.githubusercontent.com/52403795/145590469-08ecde08-7698-497a-af5e-e12b71fa9f21.png">

Any chance you could improve the error handling here on your end in order to prevent these unchecked type errors? 

Thank you! :)

**Comment by lrezek** [comment]
I have added a check for this in 0.1.0. Thanks for the feedback!
